### ISSUE TITLE
Linux build: no idea how to install and run

### ISSUE THREAD

**Issue by juju515** [imperviousai/imp-browser#14]
Hey guys, 
Just got a notification that the alpha build is ready.
Went on your website and downloaded the recommended .zip from here: https://github.com/imperviousai/imp-launcher/releases/download/v0.4.3/Impervious-linux-x64-0.4.3.zip
Unzipped and now absolutely no idea how to run it.
There are no useful README files, can't see any MAKE files or anything that would hint at the next step.

So I'm think some step-by-step guide or a nice README file would be awesome. :)
Thanks,
Regards,
OJM

**Comment by markcryptohash** [comment]
cd into the created directory and then ./Impervious

**Comment by juju515** [comment]
well that was easy... lol xD
bit embarrassing how I didn't think of trying that before opening this issue.
Thanks :) 

ps. the README file would still be good to avoid future confusion
