### ISSUE TITLE
Fix new private window page to reflect dashboard and replace URL default search engine (currently #74 in team tasks)

### ISSUE THREAD

**Issue by impervious-ai** [imperviousai/imp-browser#9]
Fix new private window page to reflect dashboard[#74](https://github.com/imperviousai/impervious-browser-plugin/issues/74)
Description

If we can’t make user accept extension in private mode and force dashboard, direct to impervious.ai for homepage
Fix CSS - Remove Extension Impervious
Replace URL bar default search engine from Amazon to Duck Duck Go

**Comment by markhandlersec** [comment]
Resolved now that the daemon serves the UI and the recent browser patches to serve this.
